### ISSUE TITLE
problem running modmap in mac

### ISSUE THREAD

**Issue by mavino** [stephensolis/modmap-experiments#1]
When I run the following command line on mac
```
marianoavino$ modmap-toolkit run-job /Users/marianoavino/Desktop/modmap/metadata/ncbi-whole.yml /Users/marianoavino/Desktop/modmap/settings.yml
```
This is the traceback I get:
```
Traceback (most recent call last):
  File "/Users/marianoavino/anaconda/bin/modmap-toolkit", line 11, in <module>
    sys.exit(main())
  File "/Users/marianoavino/anaconda/lib/python3.6/site-packages/modmap_toolkit/__main__.py", line 31, in main
    run_module.run(args)
  File "/Users/marianoavino/anaconda/lib/python3.6/site-packages/modmap_toolkit/subcommands/run_job.py", line 227, in run
    job_name = job_options['name']
 
TypeError: list indices must be integers or slices, not str
```
This is my settings.yml file:
```
# specifies the directories used for input and output
# this is required
local_dirs:
  # the directory containing zipped datasets
  archives: /Users/marianoavino/Desktop/modmap/metadata
  # the directory containing JSON metadata files
  metadata: /Users/marianoavino/Desktop/modmap/metadata
  # the directory to use for output files
  output: /Users/marianoavino/Desktop/modmap/output

# if desired, specifies an external service to use for logging
# this is optional
```

**Comment by stephensolis** [comment]
I made some improvements for the Mac, can you run `pip install --upgrade modmap-toolkit` and try again?

If that still doesn't work, can you copy and paste your `ncbi-whole.yml` here?

**Comment by mavino** [comment]
still same problem,
I am attaching my ncbi-whole.yml here (I am calling it .txt so I can attach it...)
[ncbi-whole.txt](https://github.com/stephensolis/modmap-experiments/files/1830740/ncbi-whole.txt)

**Comment by stephensolis** [comment]
I'm not sure how it happened, but that file you attached is not a job file at all.
If you try downloading ncbi-whole.yml again from: https://raw.githubusercontent.com/stephensolis/modmap-experiments/master/experiments/dengue/ncbi-whole.yml, it should work.

**Comment by mavino** [comment]
Sorry for whatever might have happened...
now I have this traceback:
```
INFO     *** started experiment 'subtype-k=4' (1/4)
INFO     using random seed value 791877043
INFO     *** started step 'select' (1/3)
INFO     started running pick_group
INFO     finished running pick_group in 0.33 seconds
INFO     started processing metadata entries
INFO     0%|          | 0/4893 [00:00<?, ?it/s]
INFO     5%|4         | 222/4893 [00:01<00:21, 221.46it/s]
INFO     10%|9         | 476/4893 [00:02<00:18, 237.54it/s]
INFO     15%|#5        | 744/4893 [00:03<00:16, 247.46it/s]
INFO     21%|##        | 1016/4893 [00:04<00:15, 253.54it/s]
INFO     26%|##6       | 1284/4893 [00:05<00:14, 256.36it/s]
INFO     32%|###1      | 1550/4893 [00:06<00:12, 257.89it/s]
INFO     37%|###7      | 1823/4893 [00:07<00:11, 259.96it/s]
INFO     43%|####2     | 2099/4893 [00:08<00:10, 261.90it/s]
INFO     48%|####8     | 2365/4893 [00:09<00:09, 262.35it/s]
INFO     54%|#####3    | 2627/4893 [00:10<00:08, 262.23it/s]
INFO     59%|#####9    | 2896/4893 [00:11<00:07, 262.82it/s]
INFO     65%|######4   | 3166/4893 [00:12<00:06, 263.39it/s]
INFO     70%|#######   | 3440/4893 [00:13<00:05, 264.16it/s]
INFO     76%|#######5  | 3707/4893 [00:14<00:04, 264.21it/s]
INFO     81%|########1 | 3974/4893 [00:15<00:03, 264.33it/s]
INFO     87%|########6 | 4242/4893 [00:16<00:02, 264.50it/s]
INFO     92%|#########2| 4513/4893 [00:17<00:01, 264.88it/s]
INFO     98%|#########7| 4784/4893 [00:18<00:00, 265.17it/s]
INFO     100%|##########| 4893/4893 [00:18<00:00, 265.42it/s]
INFO     finished processing metadata entries in 18.44 seconds
INFO     started writing metadata file
INFO     finished writing metadata file in 0.27 seconds
INFO     *** finished step 'select' (1/3) in 19.04 seconds
INFO     *** started step 'kmers' (2/3)
INFO     running command ""/Users/marianoavino/anaconda/lib/python3.6/site-packages/modmap_toolkit/scripts/generation_cgr_mac_avx2" cgr "/Users/marianoavino/Desktop/modmap/output/dengue-ncbi-whole/subtype-k=4/fasta" "/Users/marianoavino/Desktop/modmap/output/dengue-ncbi-whole/subtype-k=4/cgrs.mm-repr" 4 16"
INFO     /bin/sh: /Users/marianoavino/anaconda/lib/python3.6/site-packages/modmap_toolkit/scripts/generation_cgr_mac_avx2: No such file or directory
Traceback (most recent call last):
  File "/Users/marianoavino/anaconda/bin/modmap-toolkit", line 11, in <module>
    sys.exit(main())
  File "/Users/marianoavino/anaconda/lib/python3.6/site-packages/modmap_toolkit/__main__.py", line 32, in main
    run_module.run(args)
  File "/Users/marianoavino/anaconda/lib/python3.6/site-packages/modmap_toolkit/subcommands/run_job.py", line 277, in run
    run_experiment_steps(steps, exp_options)
  File "/Users/marianoavino/anaconda/lib/python3.6/site-packages/modmap_toolkit/subcommands/run_job.py", line 180, in run_experiment_steps
    step_runners[step_options['type']](step_options, exp_options)
  File "/Users/marianoavino/anaconda/lib/python3.6/site-packages/modmap_toolkit/job_steps/mmg.py", line 38, in run_mmg_kmers
    }, {})
  File "/Users/marianoavino/anaconda/lib/python3.6/site-packages/modmap_toolkit/job_steps/command.py", line 22, in run_command_step
    run_command_logged(options['command'], shell=True)
  File "/Users/marianoavino/anaconda/lib/python3.6/site-packages/modmap_toolkit/job_steps/command.py", line 18, in run_command_logged
    raise subprocess.CalledProcessError(process.returncode, command, None)
subprocess.CalledProcessError: Command '"/Users/marianoavino/anaconda/lib/python3.6/site-packages/modmap_toolkit/scripts/generation_cgr_mac_avx2" cgr "/Users/marianoavino/Desktop/modmap/output/dengue-ncbi-whole/subtype-k=4/fasta" "/Users/marianoavino/Desktop/modmap/output/dengue-ncbi-whole/subtype-k=4/cgrs.mm-repr" 4 16' returned non-zero exit status 127.
```

**Comment by stephensolis** [comment]
OK I fixed the problem -- please run `pip install --upgrade modmap-toolkit` and it should work, seems to be working well on my Mac.

**Comment by mavino** [comment]
OK it worked...thanks
